### ISSUE TITLE
cannot use CachyLoaderManager.shared.configure()

### ISSUE THREAD

**Issue by workingDog** [Sadmansamee/CachyKit#2]
great library, thanks.

I'm trying to use:

CachyLoaderManager.shared.configure(
    memoryCapacity: 1020,
    diskCapacity: 2024,
    maxConcurrentOperationCount: 10,
    timeoutIntervalForRequest: 3,
    diskPath: "temp",
    expiryDate: .weekly,
    isOnlyInMemory: true
)

But I get this error:

'shared' is inaccessible due to 'internal' protection level

I cannot find a way around this, any ideas?

Swift 5.1, ios 13.

**Comment by Sadmansamee** [comment]
thanks for opting out, I will check into this.

**Comment by Sadmansamee** [comment]
@workingDog I have given a fix for this issue, please update your pod repo and try again.
