### ISSUE TITLE
Cache emptied after termination of app

### ISSUE THREAD

**Issue by SlavcoPetkovski** [Sadmansamee/CachyKit#3]
Hi. Is there any way that objects are alive even after i terminate the app and open it again? They are alive while my app is active or in background, but if i kill it and open again the objects are not there anymore.

**Comment by Sadmansamee** [comment]
I'm not sure about this, need to investigate

**Comment by Sadmansamee** [comment]
Previously only cache on memory was by default, now cache on disk is enabled by default.
