### ISSUE TITLE
Persistant cache

### ISSUE THREAD

**Issue by ghost** [Sadmansamee/CachyKit#6]
Hi, 

Can we keep and recover the cache previously add after stop & start again the app now?

Thanks,

**Comment by Sadmansamee** [comment]
that's the next thing that is being planned, are you interested in making a contribution?

**Comment by d4r1091** [comment]
I believe this is now implemented 👍

**Comment by Sadmansamee** [comment]
@d4r1091 @coulonb this is implemented now by default.
