### ISSUE TITLE
Release pod new version with new tag off master

### ISSUE THREAD

**Issue by d4r1091** [Sadmansamee/CachyKit#8]
Thanks, @Sadmansamee 🙌 [for merging in my contribution](https://github.com/Sadmansamee/CachyKit/pull/7).
I believe those changes are quite crucial to the make CachyKit fully usable with `func configure` and all the improvements.
Can you please push a new release with these changes?
This way - users won't need to specify the `:branch => master` in Podfile.

**Comment by Sadmansamee** [comment]
Yes, definitely.

**Comment by Sadmansamee** [comment]
done @d4r1091
